swagger: '2.0'
info:
  title: Turkish Vocab API
  description: Turkish Vocab API on Cloud Endpoints with a Google Cloud Functions backend
  version: 1.0.0
host: turkish-vocab-api-test-bdyuqepcca-ew.a.run.app
schemes:
  - https
produces:
  - application/json
paths:
  /subscription:
    post:
      summary: Subscribe to Turkish Vocab
      operationId: hello
      x-google-backend:
        address: https://europe-west1-projects-220919.cloudfunctions.net/helloGETtest
      responses:
        '200':
          description: A successful response
          schema:
            type: string