swagger: '2.0'
info:
  title: Turkish Vocab API
  description: Turkish Vocab API on Cloud Endpoints with a Google Cloud Functions backend
  version: 1.0.0
host: $host
schemes:
  - https
produces:
  - application/json
paths:
  /subscriptions:
    post:
      summary: Subscribe to Turkish Vocab
      operationId: subscription
      x-google-backend:
        address: https://$region-$projectid.cloudfunctions.net/subscriptions$commit
      consumes:
        - application/json
      parameters:
        - in: body
          name: subscription_body
          description: The subscription request body
          schema:
            type: object
            required:
              - email
              - interests
            properties:
              email:
                type: string
              interests:
                type: array
                items:
                  type: string
      responses:
        '200':
          description: A successful response
          schema:
            type: object
            properties:
              status:
                type: string
              description:
                type: string
        '400':
          description: A bad request response
          schema:
            type: object
            properties:
              status:
                type: string
              description:
                type: string
        '404':
          description: A malformed response
          schema:
            type: object
            properties:
              status:
                type: string
              description:
                type: string
  /subscriptions/confirm:
    post:
      summary: Confirm Subscription to Turkish Vocab
      operationId: subscription_confirm
      x-google-backend:
        address: https://$region-$projectid.cloudfunctions.net/confirm$commit
      consumes:
        - application/json
      parameters:
        - in: body
          name: subscription_confirm_body
          description: The subscription confirm request body
          schema:
            type: object
            required:
              - email
              - hash
            properties:
              email:
                type: string
              hash:
                type: string
      responses:
        '200':
          description: A successful response
          schema:
            type: object
            properties:
              status:
                type: string
              description:
                type: string
        '400':
          description: A bad request response
          schema:
            type: object
            properties:
              status:
                type: string
              description:
                type: string
        '404':
          description: A malformed response
          schema:
            type: object
            properties:
              status:
                type: string
              description:
                type: string