swagger: '2.0'
info:
  title: Turkish Vocab API
  description: Turkish Vocab API on Cloud Endpoints with a Google Cloud Functions backend
  version: 1.0.0
host: $host
schemes:
  - https
produces:
  - application/json
paths:
  /subscriptions:
    post:
      summary: Subscribe to Turkish Vocab
      operationId: subscription
      x-google-backend:
        address: https://$region-$projectid.cloudfunctions.net/subscriptions$commit
      consumes:
        - application/json
      parameters:
        - in: body
          name: email
          description: The email to add to the subscription list.
          schema:
            type: object
            required:
              - email
            properties:
              email:
                type: string
              interests:
                type: array
                items:
                  type: string

      responses:
        '200':
          description: A successful response
          schema:
            type: object
            properties:
              status:
                type: string
              description:
                type: string