swagger: '2.0'
info:
  title: Turkish Vocab API
  description: Turkish Vocab API on Cloud Endpoints with a Google Cloud Functions backend
  version: 1.0.0
host: $host
schemes:
  - https
produces:
  - application/json
paths:
  /subscription:
    get:
      summary: Subscribe to Turkish Vocab
      operationId: hello
      x-google-backend:
        address: https://$region-$projectid.cloudfunctions.net/subscription$commit
      responses:
        '200':
          description: A successful response
          schema:
            type: string