name: PR
on:
  push:
    pull_request:
      types: 
        - edited
        - opened
        - reopened
      branches:
      - master

jobs:
  pr-job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2-beta
      with:
        stable: 'true'
        go-version: '1.13.7'
    - name: Run Unit Test
      run: go test .
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
       service_account_email: ${{ secrets.GCP_SA_EMAIL }}
       service_account_key: ${{ secrets.GCP_SA_KEY }}
       CLOUDSDK_PYTHON_SITEPACKAGES: 1
    - name: gcloud Set up
      run: |
         gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
    - name: Deploy Function
      run: make deploy