name: PR
on:
  pull_request:
    branches:
      - master

jobs:
  PR-Job:
    name: PR
    runs-on: ubuntu-latest
    env:
      environment : staging
    steps:
    - uses: actions/checkout@master
    - uses: deepakputhraya/action-pr-title@master
      with:
        regex: '([a-z\(\)])+:([a-z ])+'
        allowed_prefixes: 'feature,chore,fix'
        prefix_case_sensitive: false
        min_length: 5
        max_length: 50
    - uses: actions/setup-go@v2-beta
      with:
        stable: 'true'
        go-version: '1.13.7'
    - name: Run Unit Tests
      run: make test 
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: gcloud Set up
      run: |
         gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
    - name: Deploy Functions to Staging
      run: make deploy environment=${{ env.environment }} commit=$(echo ${GITHUB_SHA} | cut -c1-8)
    - name: Run Smoke Tests
      run: make smoke
    - name: Run Integration Tests
      run: make integration
    - name: Undeploy Functions from Staging
      run: make delete environment=${{ env.environment }} commit=$(echo ${GITHUB_SHA} | cut -c1-8)