name: PR
on:
  pull_request:
    branches:
      - master

jobs:
  PR-Job:
    name: PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2-beta
      with:
        stable: 'true'
        go-version: '1.13.7'
    - name: Run Unit Tests
      run: make test 
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
       service_account_email: ${{ secrets.GCP_SA_EMAIL }}
       service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: gcloud Set up
      run: |
         gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
    - name: Deploy Functions
      run: make deploy environment=staging
    - name: Run Smoke Tests
      run: make smoke
    - name: Run Integration Tests
      run: make integration
    - name: Undeploy Functions
      run: make delete environment=staging
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2.1.3
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}