name: PR
on:
  pull_request:
    branches:
      - master

jobs:
  PR-Job:
    name: PR
    runs-on: ubuntu-latest
    env:
      region : europe-west1
      GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID_STAGING}}
    steps:
    - uses: actions/checkout@master
    - uses: deepakputhraya/action-pr-title@master
      with:
        regex: '([a-z\(\)])+:([a-z ])+'
        allowed_prefixes: 'feature,chore,fix'
        prefix_case_sensitive: false
        min_length: 5
        max_length: 50
    - uses: actions/setup-go@v2-beta
      with:
        stable: 'true'
        go-version: '1.13.7'
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.2
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL_STAGING }}
        service_account_key: ${{ secrets.GCP_SA_SECRET_STAGING }}
    - name: gcloud Set up
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID_STAGING }}
    - name: Prepare Google Cloud Credentials
      id: write_file
      uses: timheuer/base64-to-file@v1.0.3
      with:
        fileName: key.json
        encodedString: ${{ secrets.GCP_SA_SECRET_STAGING }}
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.write_file.outputs.filePath }}
    - name: Run Unit Tests
      run: make test
    - name: Deploy ESP Gateway and Endpoints
      run: ./scripts/deploy_esp_endpoints.sh turkish-vocab-api-$(echo ${GITHUB_SHA} | cut -c1-8) ${{ secrets.GCP_PROJECT_ID_STAGING}} ${{ env.region }} $(echo ${GITHUB_SHA} | cut -c1-8) ${{ secrets.GCP_SA_EMAIL_STAGING }}
    - name: Deploy Functions to Staging
      run: make deploy commit=$(echo ${GITHUB_SHA} | cut -c1-8) region=${{ env.region }} serviceaccount=${{ secrets.GCP_SA_EMAIL_STAGING }}
    - name: Run Smoke Tests
      run: make smoke
    - name: Run Integration Tests
      run: make integration
    - name: Undeploy Functions from Staging
      run: make delete commit=$(echo ${GITHUB_SHA} | cut -c1-8) region=${{ env.region }}
    - name: Delete ESP Gateway and Endpoints
      run: gcloud run services delete turkish-vocab-api-$(echo ${GITHUB_SHA} | cut -c1-8) --platform managed --region ${{ env.region }} -q